title: Suspicious ADCS Denied Request
id: 994bfd6d-0a2e-481e-a861-934069fcf5f5
status: experimental
description: Detects denied request from client by Active Directory Certificate Services
references:
    - https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd299871(v=ws.10)
author: '@SerkinValery'
date: 2024/02/21
tags:
    - attack.credential_access
    - attack.t1553.004
logsource:
    product: windows
    service: application
detection:
    selection:
        Provider_Name: "Microsoft-Windows-CertificationAuthority"
        EventID: 53
    condition: selection
falsepositives:
    - Unknown
level: low
